---
- include: openshift-cluster/initialize_groups.yml
  tags:
  - always

- include: ../common/openshift-cluster/evaluate_groups.yml

- name: Subscribe hosts, update repos and update OS packages
  hosts: l_oo_all_hosts
  vars:
    openshift_deployment_type: "{{ deployment_type }}"
  roles:
  - role: rhel_subscribe
    when: deployment_type in ['atomic-enterprise', 'enterprise', 'openshift-enterprise'] and
          ansible_distribution == "RedHat" and
          lookup('oo_option', 'rhel_skip_subscription') | default(rhsub_skip, True) |
          default('no', True) | lower in ['no', 'false']
  - openshift_repos
  - os_update_latest
