---
- include: initialize_groups.yml
  tags:
  - always

- include: ../../common/openshift-cluster/std_include.yml
  tags:
  - always

- include: ../../common/openshift-cluster/redeploy-certificates/etcd.yml

- include: ../../common/openshift-cluster/redeploy-certificates/masters.yml

- include: ../../common/openshift-cluster/redeploy-certificates/nodes.yml

- include: ../../common/openshift-etcd/restart.yml

- include: ../../common/openshift-master/restart.yml

- include: ../../common/openshift-node/restart.yml

- include: ../../common/openshift-cluster/redeploy-certificates/router.yml
  when: openshift_hosted_manage_router | default(true) | bool

- include: ../../common/openshift-cluster/redeploy-certificates/registry.yml
  when: openshift_hosted_manage_registry | default(true) | bool
