---
- include: ../openshift-cluster/initialize_groups.yml
  tags:
  - always

- include: ../../common/openshift-cluster/std_include.yml
  tags:
  - always

- include: ../../common/openshift-node/restart.yml
  vars:
    openshift_deployment_type: "{{ deployment_type }}"
