---
- include: ../openshift-cluster/initialize_groups.yml

- include: ../../common/openshift-node/scaleup.yml
  vars:
    openshift_cluster_id: "{{ cluster_id | default('default') }}"
    openshift_debug_level: "{{ debug_level | default(2) }}"
    openshift_deployment_type: "{{ deployment_type }}"
    openshift_master_etcd_hosts: "{{ groups.etcd | default([]) }}"
    openshift_master_etcd_port: 2379
